name: Build Static Android Python

on:
  workflow_dispatch:
  push:
    branches: [main, '3.*', Try]
  pull_request:
    branches: [main, '3.*']

jobs:
  build-static:
    name: Build Static Python (${{ matrix.version }})
    runs-on: macos-14
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 3.13
            branch: 3.13
          - version: 3.14
            branch: 3.14
          - version: 3.15
            branch: main

    env:
      CC: clang
      CXX: clang++
      LD: clang
      AR: llvm-ar
      NM: llvm-nm
      RANLIB: llvm-ranlib
      LLVM_PATH: /opt/homebrew/opt/llvm/bin
      ARCH: aarch64
      CFLAGS: "-fPIC -static"
      LDFLAGS: "-static"
      ANDROID_HOME: /Users/runner/Library/Android/sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up environment
        run: |
          set -euxo pipefail
          brew update
          brew install readline llvm lld mpdecimal || true
          brew uninstall gcc || true
          echo "$LLVM_PATH" >> $GITHUB_PATH
          export PATH="$LLVM_PATH:$PATH"
          # Set up Android SDK
          curl -L https://dl.google.com/android/repository/commandlinetools-mac-11076708_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_HOME
          # Create license directory and pre-accept licenses to avoid interactive prompt
          mkdir -p $ANDROID_HOME/licenses
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n" > $ANDROID_HOME/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd\n" > $ANDROID_HOME/licenses/android-sdk-preview-license
          echo -e "\nd975f751698b51a0c1248a6993fecb955d3f1b3f\n" > $ANDROID_HOME/licenses/android-sdk-arm-dbt-license
          # Install platform-tools
          $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" || true
          # Verify licenses
          $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

      - name: Cache LLVM and dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
            /opt/homebrew/Cellar/llvm
          key: llvm-static-${{ runner.os }}-${{ hashFiles('.github/workflows/build-static-android.yml') }}

      - name: Checkout CPython repository
        uses: actions/checkout@v5
        with:
          repository: python/cpython
          ref: ${{ matrix.branch }}
          path: cpython-${{ matrix.version }}
          fetch-depth: 1

      - name: Apply patches (only for 3.13)
        if: matrix.version == '3.13'
        working-directory: ./cpython-${{ matrix.version }}
        run: |
          set -euxo pipefail
          curl -L https://raw.githubusercontent.com/yubrajbhoi/termux-python/refs/heads/main/termux.patch -o termux.patch
          curl -L https://raw.githubusercontent.com/plfj/py-build/refs/heads/main/as13.patch -o as13.patch
          git apply ./termux.patch || echo "⚠️ termux.patch apply failed — continuing."
          git apply ./as13.patch || echo "⚠️ as13.patch apply failed — continuing."

      - name: Build static CPython for Android
        working-directory: ./cpython-${{ matrix.version }}/Android
        run: |
          set -euxo pipefail
          ./android.py ci --fast-ci aarch64-linux-android -- --without-shared --without-static-libpython
          echo "✅ Static build finished for version ${{ matrix.version }}"
          ls -lh ../cross-build/aarch64-linux-android/dist || echo "⚠️ Package output not found"

      - name: Verify static binary
        working-directory: ./cpython-${{ matrix.version }}/cross-build/aarch64-linux-android
        run: |
          set -euxo pipefail
          BINARY=$(find prefix -name python -type f -executable || find install -name python -type f -executable)
          if [ -z "$BINARY" ]; then
            echo "⚠️ Python binary not found"
            exit 1
          fi
          file "$BINARY" | grep -q "statically linked" || (echo "⚠️ Binary is not statically linked" && exit 1)
          echo "✅ Verified static binary: $BINARY"

      - name: Upload static Python archive
        uses: actions/upload-artifact@v4
        with:
          name: python-static-${{ matrix.version }}
          path: cpython-${{ matrix.version }}/cross-build/aarch64-linux-android/dist/python-*.tar.gz
          if-no-files-found: error
