name: Build compression libs for Android (aarch64)

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-android:
    name: Android (aarch64) compression libs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake ninja-build curl unzip tar autoconf automake libtool git

      - name: Download Android NDK (r28c)
        run: |
          curl -L https://dl.google.com/android/repository/android-ndk-r28c-linux.zip -o ndk.zip
          unzip -q ndk.zip
          mv android-ndk-* $HOME/android-ndk

      - name: Setup toolchain
        run: |
          export ANDROID_NDK=$HOME/android-ndk
          export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64
          export API=21
          echo "ANDROID_NDK=$ANDROID_NDK" >> $GITHUB_ENV
          echo "TOOLCHAIN=$TOOLCHAIN" >> $GITHUB_ENV
          echo "API=$API" >> $GITHUB_ENV
          echo "CC=$TOOLCHAIN/bin/aarch64-linux-android${API}-clang" >> $GITHUB_ENV
          echo "CXX=$TOOLCHAIN/bin/aarch64-linux-android${API}-clang++" >> $GITHUB_ENV
          echo "AR=$TOOLCHAIN/bin/llvm-ar" >> $GITHUB_ENV
          echo "RANLIB=$TOOLCHAIN/bin/llvm-ranlib" >> $GITHUB_ENV
          echo "STRIP=$TOOLCHAIN/bin/llvm-strip" >> $GITHUB_ENV
          echo "PATH=$TOOLCHAIN/bin:$PATH" >> $GITHUB_ENV

      # ────────────── zlib ──────────────
      - name: Build zlib
        run: |
          curl -L https://zlib.net/zlib-1.3.1.tar.gz -o zlib.tar.gz
          tar -xzf zlib.tar.gz
          mv zlib-* zlib
          mkdir build-zlib && cd build-zlib
          cmake ../zlib \
            -DCMAKE_SYSTEM_NAME=Android \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_ANDROID_NDK=$ANDROID_NDK \
            -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
            -DCMAKE_ANDROID_API=$API \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$PWD/../android-libs/aarch64-linux-android \
            -DBUILD_SHARED_LIBS=OFF \
            -DZLIB_BUILD_EXAMPLES=OFF \
            -G Ninja
          cmake --build . --config Release
          cmake --install .

      # ────────────── bzip2 ──────────────
      - name: Build bzip2
        run: |
          curl -L https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz -o bzip2.tar.gz
          tar -xzf bzip2.tar.gz
          cd bzip2-1.0.8
          # Modify Makefile to skip tests
          sed -i 's/all: libbz2.a bzip2 bzip2recover test/all: libbz2.a bzip2 bzip2recover/' Makefile
          make CC="$CC" AR="$AR" RANLIB="$RANLIB" CFLAGS="-fPIC" PREFIX=$GITHUB_WORKSPACE/android-libs/aarch64-linux-android all
          make CC="$CC" AR="$AR" RANLIB="$RANLIB" CFLAGS="-fPIC" PREFIX=$GITHUB_WORKSPACE/android-libs/aarch64-linux-android install

      # ────────────── xz (standard lzma) ──────────────
      - name: Build xz (standard lzma)
        run: |
          curl -L https://tukaani.org/xz/xz-5.2.10.tar.gz -o xz.tar.gz
          tar -xzf xz.tar.gz
          cd xz-5.2.10
          ./configure \
            --host=aarch64-linux-android \
            --prefix=$GITHUB_WORKSPACE/android-libs/aarch64-linux-android \
            --disable-shared --enable-static --with-pic \
            --disable-xz --disable-xzdec --disable-tests \
            --disable-lzmadec --disable-scripts \
            CC="$CC" AR="$AR" RANLIB="$RANLIB"
          make
          make install

      # ────────────── gzip ──────────────
      - name: Build gzip
        run: |
          curl -L https://ftp.gnu.org/gnu/gzip/gzip-1.13.tar.gz -o gzip.tar.gz
          tar -xzf gzip.tar.gz
          cd gzip-1.13
          ./configure \
            --host=aarch64-linux-android \
            --prefix=$GITHUB_WORKSPACE/android-libs/aarch64-linux-android \
            --disable-dependency-tracking \
            --disable-testing \
            CC="$CC" AR="$AR" RANLIB="$RANLIB" \
            CPPFLAGS="-I$GITHUB_WORKSPACE/android-libs/aarch64-linux-android/include" \
            LDFLAGS="-L$GITHUB_WORKSPACE/android-libs/aarch64-linux-android/lib"
          make
          make install

      # ────────────── Package all libs ──────────────
      - name: Package all libraries
        run: |
          cd $GITHUB_WORKSPACE/android-libs
          tar -czf compression-libs-aarch64-android.tar.gz aarch64-linux-android
          mv compression-libs-aarch64-android.tar.gz $GITHUB_WORKSPACE/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "compression_libs"
          name: "Compression Libraries (zlib, bzip2, xz/lzma, gzip)"
          files: compression-libs-aarch64-android.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
