name: Build and Release Custom LLVM 21.1.3 for Android NDK r29

on:
  push:
    tags:
      - 'llvm*'  # Trigger release on pushing a tag like v1.0.0
    branches:  # Trigger build on every push to any branch
      - '**'   # Matches all branches

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 build-essential git cmake ninja-build curl unzip libxml2-dev pkg-config zlib1g-dev xz-utils

      - name: Download Android NDK r29
        run: |
          NDK_URL="https://dl.google.com/android/repository/android-ndk-r29-linux.zip"
          curl -f -o android-ndk-r29-linux.zip "$NDK_URL" || {
            echo "Error: Failed to download NDK from $NDK_URL. Check if the URL is still valid or try https://developer.android.com/ndk/downloads"
            exit 1
          }
          unzip android-ndk-r29-linux.zip -d $HOME
          export NDK=$HOME/android-ndk-r29
          echo "NDK=$HOME/android-ndk-r29" >> $GITHUB_ENV

      - name: Clone Android NDK source for patches
        run: |
          git clone https://github.com/android/ndk.git
          cd ndk
          git checkout r29

      - name: Download LLVM 21.1.3 prebuilt binary
        run: |
          LLVM_URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.3/LLVM-21.1.3-Linux-X64.tar.xz"
          curl -f -L -o LLVM-21.1.3-Linux-X64.tar.xz "$LLVM_URL" || {
            echo "Error: Failed to download LLVM from $LLVM_URL. Check the URL or GitHub releases."
            exit 1
          }
          tar -xf LLVM-21.1.3-Linux-X64.tar.xz -C $HOME
          mv $HOME/LLVM-21.1.3-Linux-X64 $HOME/llvm21-install
          echo "LLVM_INSTALL=$HOME/llvm21-install" >> $GITHUB_ENV

      - name: Apply Android-specific patches
        run: |
          cd $GITHUB_WORKSPACE/ndk
          ./build/tools/apply-llvm-patches.py --llvm-path $HOME/llvm21-install --revision r29 || {
            echo "Warning: Patch application failed. Continuing with unpatched LLVM 21.1.3."
          }

      - name: Verify LLVM installation
        run: |
          $LLVM_INSTALL/bin/clang --version | grep "clang version 21.1.3" || {
            echo "Error: LLVM version mismatch. Expected 21.1.3."
            exit 1
          }

      - name: Package the build
        run: |
          cd $GITHUB_WORKSPACE
          tar -czf llvm21-android-ndk-r29-linux.tar.gz -C $HOME llvm21-install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm21-build
          path: llvm21-android-ndk-r29-linux.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Only create release for tagged pushes
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: llvm21-build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: llvm21-android-ndk-r29-linux.tar.gz
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Custom LLVM 21.1.3 build for Android NDK r29 (Linux host).
            Built on ${{ github.event.head_commit.message }}.
            Based on prebuilt LLVM 21.1.3 (X64) with Android NDK r29 patches (if applied successfully).
            Supports Android targets: X86, ARM, AArch64.
          draft: false
          prerelease: false
